# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbeba1bb8eaa7973ddbed2fe7b1dd914eabaea9f4ecfa018c712bcdd7ddc04afd300e95f76fbcca6ad8f9c3d49c7a7bc9a386d2e9bcb33c545739171265b2ce2

test:
  secret_key_base: 610b79258cc3111ad8989332acbc4d6155389f7856f9f11cc75b8bf45eb63aedd57e19e667349d8e673aea4f9c8c1552ccfbfaf041c9a29049fe79c4cf538974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
